name: Just a workflow_dispatch test from main branch (Selenoid test)

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Which test need to launch
        options:
        - advanced_test
        - base_test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull project
      uses: actions/checkout@v3
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v2
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup different needs
      run: python -m pip install pytest-zebrunner && python -m pip install selenium && python -m pip install pytest

    - name: Run tests
      run: cd sample-pytest && python -m pytest -s -v tests/${{ github.event.inputs.name }}.py